/*   misc   */
#define MarioProc1                      geo_move_mario_part_from_parent
#define CtrlMarioEye                    geo_switch_mario_eyes
#define CtrlMarioWaist                  geo_mario_tilt_torso
#define CtrlMarioHead                   geo_mario_head_rotation
#define CtrlMarioHand                   geo_switch_mario_hand
#define CtrlMarioTaking                 geo_switch_mario_hand_grab_pos
#define CtrlMarioAlpha                  geo_mirror_mario_set_alpha
#define CtrlMarioLOD                    geo_switch_mario_stand_run
#define CtrlMarioRenderMode             geo_switch_mario_cap_effect