name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      # Runs a set of commands using the runners shell
    - name: Install Dependencies 
      run: |
          sudo apt install -y binutils-mips-linux-gnu build-essential git libcapstone-dev pkgconf python3 bsdmainutils
          wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
          sudo dpkg -i qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
          wget https://download2281.mediafire.com/dg8audcexqqg7A741WXIiZSTPytKUv6Uec0AFp7GSJ73IDYLxoOLXWnnoKLhJs9w5Nb-6pdIhwm0I-AyIW6oO166Y6-GjBn5Pt06nUNEeOP8K12W7zquQGEltRmLWRw4SMsIQPlmIPVH6sFs6S2YK9HzB2-cNkcGxyZiRqqBKFrg0g/p043nwcxf1fah7q/Super+Mario+64+%28J%29+%5B%21%5D.z64
          mv "Super+Mario+64+(J)+[!].z64" baserom.jp.z64
          chmod +x *
          sudo apt install build-essential pkg-config git binutils-mips-linux-gnu python3 zlib1g-dev libaudiofile-dev libcapstone-dev
    - name: Compile
      run: make -j32 VERSION=jp
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linuxBuild
        path: 'build/jp/sm64.jp.z64'
